=== Fl0f3nce/test-responsive/web/WEB-INF/xsd/ielm-scenario.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.hs-coburg.de/e-learning/ielm-scenarios"
           elementFormDefault="qualified">

  <xs:element name="scenario">
    <xs:complexType>
      <xs:all>
        <xs:element name="name" type="xs:string" />
        <xs:element name="description" type="xs:string" />
        <xs:element name="level" type="xs:string" />
        <xs:element name="author" type="xs:string" />
        <xs:element name="date" type="xs:date" />
        <xs:element name="category" type="xs:string" />
        <xs:element name="contact" type="xs:string" />
        <xs:element name="content">
          <xs:complexType>
            <xs:sequence>
              <xs:any processContents="strict" namespace="##other" minOccurs="1" maxOccurs="1"/>
              <!--<xs:any processContents="lax" minOccurs="1" maxOccurs="1"/>-->
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:all>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Fl0f3nce/test-responsive/web/WEB-INF/scenarios/scenario-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<scenario       xmlns="http://www.hs-coburg.de/e-learning/ielm-scenarios" 
            xmlns:p = "http://www.hs-coburg.de/e-learning/eltest"
            xsi:schemaLocation="http://www.hs-coburg.de/e-learning/ielm-scenarios ../xsd/ielm-scenario.xsd
                              http://www.hs-coburg.de/e-learning/eltest ../xsd/eltest-content.xsd"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <name>Szenario 1</name>	
  <description>Ein erstes Szenarion zum iELM ELtest</description>
  <level>0</level>
  <author>D. Wi&amp;szlig;mann</author>
  <date>2016-03-04</date>
  <category>Anschauung</category>
  <contact>dieter.wissmann@hs-coburg.de</contact>
  <content>
    <p:eltest_content>     
      <!-- wss 20160304: ielm specific content -->
      <p:specific_desc>Das ist der spezifische Inhalt des Szenario 1 zum iELM ELtest. Es ist leider nur ein einfacher Text.</p:specific_desc>
      
    </p:eltest_content>
  </content>
</scenario>
